### ISSUE TITLE
option for placement

### ISSUE THREAD

**Issue by nagim** [billryan/gitbook-plugin-tags#1]
Hi,

This plugin is really neat!
One request: could you please implement an option for putting the tags at the bottom of the page? Currently it's placed before the first paragraph, it would be great if we could place it after the last paragraph.

Thanks a lot!

Cheers,
Imre

**Comment by billryan** [comment]
It is a good idea to add an option for placement. You can config it via

```
    "pluginsConfig": {
        "tags": {
            "placement": "bottom"
        }
    }
```

**Comment by nagim** [comment]
Wow, so quickly!
This is great, thanks a lot.
