### ISSUE TITLE
asciidoc support

### ISSUE THREAD

**Issue by nagim** [billryan/gitbook-plugin-tags#2]
Hi,

Does the current version supports AsciiDoc syntax, or only Markdown?
If it does not, could you please implement AsciiDoc support?

Thanks,
Imre

**Comment by billryan** [comment]
This plugin only supports Markdown currently, I will add AsciiDoc support later. Thanks for your feedback.

**Comment by billryan** [comment]
Added asciidoc support in latest version 1.4.0

**Comment by nagim** [comment]
Really great, thanks a lot!
I will try it soon!

One really minor comment: in your example book, in the AsciiDoc file, the tag icon and styling of the tags don't work.

**Comment by billryan** [comment]
I forgot to update the demo website. Now tags fontawesome icon and styling are available for AsciiDoc. 🍺

**Comment by nagim** [comment]
Kudos for you, mate! :beers: Thanks!
