### ISSUE TITLE
lacking github-slugid causing gitbook build failure

### ISSUE THREAD

**Issue by juniway** [billryan/gitbook-plugin-tags#3]
book.json
{
    "title": "juniway",
    "author": "_",
    "description": "_",
    "extension": null,
    "generator": "website",
    "isbn": "",
    "links": {
        "sharing": {
            "all": null
        },
    },
    "output": null,
    "styles": {
        "website": "styles/website.css"
    },  
    "plugins": ["disqus","codeblock-filename", "multipart", "tags"],
    "pluginsConfig": {
        "disqus": {
            "shortName": "juniway"
        }
    },
    "variables": {}
}

目前为了编译通过，我已经把 tags 插件去掉。

本地已经执行下列命令安装 tags 相关 plugin 和依赖 
npm install gitbook-plugin-tags --save-dev
gitbook install
npm install github-slugid -g 

并且本地gitbook 编译成功， gitbook server 成功

源码 push 到远程 gitbook repo 之后， gitbook 如邮件截图所示编译失败。

请帮忙解决，十分感谢。

**Comment by billryan** [comment]
原来是 tags 插件里忘写 dependencies 了...
Fixed. Thanks for your feedback.

P.S. 你 GitHub repo 中的 package.json 不需要 push, 建议 git rm 处理掉，GitBook 里所有插件应该由 `gitbook install` 处理而不是用 npm, 如果需要 npm 手动装，基本上是 dependencies 的问题。

**Comment by juniway** [comment]
ok， 谢谢你的建议。请问现在我需要怎么处理才能解决之前的编译问题啊？

**Comment by billryan** [comment]
你这边不需要处理，下一次 push 时就不会有这个问题了，本地的话 gitbook install 即可
