### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by sxhmilyoyo** [billryan/gitbook-plugin-tags#7]
I follow the instructions but it doesn't work. How to add dependency into a file? Thanks.

**Comment by billryan** [comment]
Add plugins `tags` into your `book.json`, then put `tags: tag1, tag2` in your markdown files.

P.S. If it is still not working, show me your book repository and I will check it when I am available.

**Comment by sxhmilyoyo** [comment]
It works in read mode. I thought it would show in markdown preview. Thank you.
